### ISSUE TITLE
Typo in pull quote on "Obligatory post about re-starting my personal site."

### ISSUE THREAD

**Issue by nicholasohrn** [hbuchel/heather-buchel.com#9]
https://github.com/hbuchel/heather-buchel.com/blob/51d50b37c5b2231d4723d4963aedc0ec960b4798/content/blog/2023/07/obligatory-post.md?plain=1#L15

The word `buiding` should be `building`, presumably. Love the design of your site, by the way.

**Comment by hbuchel** [comment]
Hey @nicholasohrn thanks for the kind words and for the heads up on the typo! Fixed in https://github.com/hbuchel/heather-buchel.com/pull/11
